SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 3.5  # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

FPS=60
PLAYER_RADIUS=20
PLAYER_TURN_SPEED=1
PLAYER_SPEED=1
PLAYER_SHOOT_SPEED=50
PLAYER_SHOT_RADIUS=5
PLAYER_SHOT_LIFE_TIME=0.4
PLAYER_SHOT_COOLDOWN=0.2

MAX_ASTEROIDS=20
SHOT_RADIUS=5
