SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 20 # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS


FPS=60
PLAYER_RADIUS=20
PLAYER_TURN_SPEED=1
PLAYER_SPEED=3
PLAYER_SHOOT_SPEED=2
PLAYER_SHOT_RADIUS=5
PLAYER_SHOT_LIFE_TIME=0.4
PLAYER_SHOT_COOLDOWN=3

MAX_ASTEROIDS=2
SHOT_RADIUS=5
